// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

    //show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8eht8lGlwKrMalhkNgSfob0dv0VCfeU',
    appId: '1:917781965675:web:3eff9f998fb9226c007a2e',
    messagingSenderId: '917781965675',
    projectId: 'point-and-learn',
    authDomain: 'point-and-learn.firebaseapp.com',
    storageBucket: 'point-and-learn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEWlOwayVcSH5RusxsOgUbwyl4blKeWo',
    appId: '1:917781965675:android:d1794409d9c7680d007a2e',
    messagingSenderId: '917781965675',
    projectId: 'point-and-learn',
    storageBucket: 'point-and-learn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCg7VRN5WvYT0iiiakTqK0J9LTymkawaQ',
    appId: '1:917781965675:ios:5b9862747c1dd846007a2e',
    messagingSenderId: '917781965675',
    projectId: 'point-and-learn',
    storageBucket: 'point-and-learn.firebasestorage.app',
    iosBundleId: 'com.example.pointandlearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCg7VRN5WvYT0iiiakTqK0J9LTymkawaQ',
    appId: '1:917781965675:ios:5b9862747c1dd846007a2e',
    messagingSenderId: '917781965675',
    projectId: 'point-and-learn',
    storageBucket: 'point-and-learn.firebasestorage.app',
    iosBundleId: 'com.example.pointandlearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw8eht8lGlwKrMalhkNgSfob0dv0VCfeU',
    appId: '1:917781965675:web:af644da5923db824007a2e',
    messagingSenderId: '917781965675',
    projectId: 'point-and-learn',
    authDomain: 'point-and-learn.firebaseapp.com',
    storageBucket: 'point-and-learn.firebasestorage.app',
  );
}
